version: '3.7'
services:
  frontend:
    container_name: vue-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - '8080:3000'