version: '3.7'
services:
  frontend:
    dns: 1.1.1.1
    container_name: vue-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 8000
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - "8000:8000"
