version: '3.7'
services:
  frontend:
    container_name: vue-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 8000
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - "8000:8000"
    depends_on:
      - adminer
  db:
    image: postgres
    restart: always
    ports:
      - 8432:5432
    environment:
      POSTGRES_USER: transcended
      POSTGRES_PASSWORD: transcended
      POSTGRES_DB: pong_db
    volumes:
      - transcendence_db:/var/lib/postgresql
  backend:
    container_name: nestjs-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/app'
      - '/app/node_modules'
    ports:
      - "8090:8090"
    expose:
      - 8090
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    depends_on:
      - backend
    ports:
      - 8100:8080
volumes:
  transcendence_db: {}