version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 8432:5432
    environment:
      POSTGRES_USER: transcended
      POSTGRES_PASSWORD: transcended
      POSTGRES_DB: pong_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8100:8080
